### PR TITLE
PAR-32: al parent to java 7

### PR DESCRIPTION
**Pull request by janvenstermans**

### CODE REVIEW

**Comment by oliverm-be** [comment]
Oliver May: +1 (binding)

**Comment by jandm** [comment]
+1 (binding)

**Comment by janvenstermans** [comment]
Jan Venstermans: +1

**Comment by janvenstermans** [comment]
Vote count: 
Oliver May: +1 (binding)
Jan De Moerloose: +1 (binding)

Jan Venstermans: +1

Vote successful

**Pull request merged**
