### PR TITLE
update copyright headers to 2016

### PR DESCRIPTION
**Pull request by streulma**

### CODE REVIEW

**Comment by olivermay** [comment]
Matthias can you create an issue in JIRA and re-do the pull request with the correct jira issue? (can all be a single issue MAJ-... for copyright)

**Comment by olivermay** [comment]
@streulma can you please have a look at this?

thanks!

**Comment by streulma** [comment]
I can't login to JIRA anymore. User account is disabled. :-P

**Comment by streulma** [comment]
Oliver, can you please remove this pull request?

**Pull request closed without merging**
